* Introduction
Once upon a time when people talked about developing WordPress plug-ins, they usually also referred to boiler templates. A very famous one was

https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/

Early year 2022 I published multipass boilerplate templates in bash and php that handle a particular directory.
This is a set of scripts that handles boilerplate templates written in bash and php with lots of examples:

https://github.com/kresimir71/tttemplates

It is also possible to process file in multiple passes.

This is a suite of scripts that processes boilerplate templates written in bash and php. It works like this:

The utility takes a directory tree of template files of following sorts:

#+BEGIN_SRC

 path/name
 path/name.phptt
 path/name.php.phptt

#+END_SRC

where 'path' and 'name' can also be string templates like

#+BEGIN_SRC

 dir1_{ttt_var1}/dir2_{ttt_var2}/file_{ttt_var3}.txt.phptt

#+END_SRC

where the variables like 'ttt_var1' will be defined in the shell script settings.sh which is an input to the processing. The prefix 'ttt_' for the variables is required.

The files of the form 

#+BEGIN_SRC

 path/name.php.phptt

#+END_SRC

will be processed by 'php' by using 

#+BEGIN_SRC

 require 'settings.php' 

#+END_SRC

first, where settings.php is an input configuration file to the process. The result will be the file

#+BEGIN_SRC

 path/name.php

#+END_SRC

in which a search/replace will be done:

#+BEGIN_SRC

 >?php with <?php 
      and 
    ?< with ?>

#+END_SRC

(That defines how template that has to result in php source is processed: php template which produces php!)

The files of the form 

#+BEGIN_SRC

 path/name.phptt

#+END_SRC

will be processed by 'php' by using 

#+BEGIN_SRC

 require 'settings.php' 

#+END_SRC

first, where settings.php is an input configuration file to the process. The result will be the file

#+BEGIN_SRC

 path/name

#+END_SRC

The other files which do not have .phptt extension suffix will not be processed and will be left as they are.

It is also possible to process file in multiple passes. When a file has the form

#+BEGIN_SRC
 name.phptt.phptt
 name.phptt.phptt.phptt
 name.phptt.phptt.phptt.phptt
 name.phptt.phptt.phptt.phptt.phptt
#+END_SRC

then php will be called multiple times for that file. The inner blocks of php then use the following delimiters:

#+BEGIN_SRC
 >?php and ?<
 >??php and ??<
 >???php and ???<
 >????php and ????<
 >?????php and ?????<
#+END_SRC

* Source
  [[./src/process_tttemplate.org][src/process_tttemplate.org]]
  
* Examples

To prepare the suite for usage, first checkout the project from Github:

#+BEGIN_SRC
git clone https://github.com/kresimir71/tttemplates.git
cd tttemplates
BASEDIR01=`pwd`
#+END_SRC

** testtemplate

#+BEGIN_SRC
#rm -rf /tmp/testtemplate_result
cd examples/testtemplate/templatedir
[ "$BASEDIR01" != ""  ] && cd $BASEDIR01/examples/testtemplate/templatedir
bash ../../../src/process_tttemplate.org "`pwd`"/../config.sh "`pwd`"/../config.php /tmp/testtemplate_result
cd ../../..

#+END_SRC
   
** automake

#+BEGIN_SRC
#rm -rf /tmp/automake_result
cd examples/automake/templatedir
[ "$BASEDIR01" != ""  ] && cd $BASEDIR01/examples/automake/templatedir
bash ../../../src/process_tttemplate.org "`pwd`"/../config.sh "`pwd`"/../config.php /tmp/automake_result
cd ../../..

#+END_SRC

** wpplugin

#+BEGIN_SRC
#rm -rf /tmp/wpplugin_result
cd examples/wpplugin/templatedir
[ "$BASEDIR01" != ""  ] && cd $BASEDIR01/examples/wpplugin/templatedir
bash ../../../src/process_tttemplate.org "`pwd`"/../config.sh "`pwd`"/../config.php /tmp/wpplugin_result
cd ../../..
#+END_SRC
   
** wp admin customizer

This has worked before. Now at least for illustration.

*** textarea or color  section

#+BEGIN_SRC
#rm -rf /tmp/wpcustomizer_result
cd examples/wpcustomizer/templatedir
[ "$BASEDIR01" != ""  ] && cd $BASEDIR01/examples/wpcustomizer/templatedir
bash ../../../src/process_tttemplate.org "`pwd`"/../config.sh "`pwd`"/../config.php /tmp/wpcustomizer_result
cd ../../..
#+END_SRC
    
** php script with arguments

#+BEGIN_SRC
#rm -rf /tmp/phpargs_result
cd examples/phpargs/templatedir
[ "$BASEDIR01" != ""  ] && cd $BASEDIR01/examples/phpargs/templatedir
bash ../../../src/process_tttemplate.org "`pwd`"/../config.sh "`pwd`"/../config.php /tmp/phpargs_result
cd ../../..
#+END_SRC
   
** testtemplate02 5 passes

#+BEGIN_SRC

#rm -rf /tmp/testtemplate02_result
cd examples/testtemplate02/templatedir
[ "$BASEDIR01" != ""  ] && cd $BASEDIR01/examples/testtemplate02/templatedir
bash ../../../src/process_tttemplate.org "`pwd`"/../config.sh "`pwd`"/../config.php /tmp/testtemplate02_result
cd ../../..

#+END_SRC
