export   ttt_plugin_main_dir='kk71-appointments-filler'
export   ttt_plugin_slug='kk71-appointments-filler'
export   ttt_plugin_slug2='kk71appointmentsfiller'
export   ttt_Plugin_Name='kk71 Appointments Filler'
export   ttt_Plugin_URI='http://wordpress.org/plugins/kk71-appointments-filler'
export   ttt_Github_URI='kresimir71/kk71-appointments-filler'
export   ttt_Description='To fill the appontments+ configuration with some specific items.'
export   ttt_Author='K.Karamazen'
export   ttt_Author_URI='https://github.com/kresimir71'
export   ttt_Version='0.0.0.1'
export   ttt_Text_Domain='kk71-appointments-filler'
export   ttt_License='GPLv3 or later'
export   ttt_License_URI='http://www.gnu.org/licenses/gpl-3.0.txt'
export   ttt_Provides='KK71AppointmentsFiller'
  
export   ttt_package='KK71AppointmentsFiller'
export   ttt_author='K.Karamazen'
export   ttt_license='GNU General Public License, version 3'
export   ttt_copyright='2012-2019 K.Karamazen'
export   ttt_plugin_class='kk71-appointments-filler-plugin'
   
